import { IPage } from "./IPage";
import { ITodoListTodos } from "./ITodoListTodos";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListTodos = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoListTodos[];
};
