import { tags } from "typia";

/**
 * Represents the complete todo list app user account entity.
 *
 * Includes identification, authentication credentials (password hash),
 * verification status, and timestamps.
 *
 * Deleted_at is nullable and indicates soft deletion status.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoListAppTodoListAppUsers = {
  /** Primary Key identifying the user. */
  id: string & tags.Format<"uuid">;

  /** User's unique email address for login and identity verification. */
  email: string;

  /** Hashed password for user authentication. */
  password_hash: string;

  /** Indicates whether the user's email address has been verified. */
  email_verified: boolean;

  /** Timestamp when the user account was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp when the user account was last updated. */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp indicating when the user account was soft deleted, if
   * applicable.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoListAppTodoListAppUsers {
  /**
   * A safe view of a todo list app user account excluding sensitive fields
   * such as password hashes.
   *
   * This entity represents a user account with essential public properties.
   *
   * Deleted_at is nullable and only included when the user is soft deleted.
   */
  export type ISafe = {
    /** Primary Key identifying the user. */
    id: string & tags.Format<"uuid">;

    /** User's unique email address for login and identity verification. */
    email: string;

    /** Indicates whether the user's email address has been verified. */
    email_verified: boolean;

    /** Timestamp when the user account was created. */
    created_at: string & tags.Format<"date-time">;

    /** Timestamp when the user account was last updated. */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Timestamp indicating when the user account was soft deleted, if
     * applicable.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Request parameters for searching and paginated retrieval of todo list app
   * user accounts.
   *
   * Supports filtering, sorting, and paging options to refine the list search
   * results.
   *
   * Parameters such as page, limit, search text, email verification status,
   * and sorting can be used.
   */
  export type IRequest = {
    /** Page number of the paginated list. */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /** Limitation of records per a page. */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /** Search term for filtering users by email or other indexed properties. */
    search?: string | null | undefined;

    /** Filter by whether the user's email is verified. */
    email_verified?: boolean | null | undefined;

    /** Column name to sort the results by. */
    sort_by?: string | null | undefined;

    /** Sort order: ascending or descending. */
    order?: string | null | undefined;
  };

  /**
   * Details for updating a todo list app user account.
   *
   * Properties are optional and can be updated selectively.
   *
   * Includes email, password hash, email verification status, and timestamps.
   *
   * Note that ownership and immutable fields such as the user ID are not
   * included and cannot be updated here.
   */
  export type IUpdate = {
    /** User's unique email address for login and identity verification. */
    email?: string | undefined;

    /** Hashed password for user authentication. */
    password_hash?: string | undefined;

    /** Indicates whether the user's email address has been verified. */
    email_verified?: boolean | undefined;

    /** Timestamp when the user account was created. */
    created_at?: (string & tags.Format<"date-time">) | undefined;

    /** Timestamp when the user account was last updated. */
    updated_at?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Timestamp indicating when the user account was soft deleted, if
     * applicable.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary information for todo list app user accounts.
   *
   * This simplified schema includes essential identification and status
   * fields used in list views or minimal user representations. It omits
   * sensitive fields such as password hashes to ensure security and privacy.
   *
   * The schema aligns with the todo_list_app_users table structure,
   * reflecting user public information relevant to most application
   * features.
   */
  export type ISummary = {
    /**
     * Unique identifier of the todo list app user.
     *
     * This is the primary key for identifying user accounts in the system.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The unique email address of the user.
     *
     * This email is used for login and communication and must be unique
     * across all users.
     */
    email: string;

    /**
     * Indicates whether the user's email address has been verified.
     *
     * A verified email means the user has confirmed ownership of the email
     * address, enabling full access to the application features.
     */
    email_verified: boolean;

    /**
     * Timestamp when the user account was created.
     *
     * This field records the exact time the account was initially
     * registered and persisted.
     */
    created_at: string & tags.Format<"date-time">;
  };
}
