import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITodoListAdmin } from "../../../../structures/ITodoListAdmin";

/**
 * Authenticate administrator login.
 *
 * Authenticate administrator using email and password credentials stored
 * securely in todo_list_admin. Returns JWT access and refresh tokens if
 * credentials are valid. The system enforces unique email addresses and
 * password hashes for authentication. This login is essential for admin users
 * to securely access all system functions. The endpoint accepts email and
 * password in the request body and returns authorized tokens for subsequent
 * requests.
 *
 * @param props.connection
 * @param props.body Admin login credentials
 * @setHeader token.access Authorization
 *
 * @path /auth/admin/login
 * @accessor api.functional.auth.admin.login.loginAdmin
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function loginAdmin(
  connection: IConnection,
  props: loginAdmin.Props,
): Promise<loginAdmin.Response> {
  const output: loginAdmin.Response =
    true === connection.simulate
      ? loginAdmin.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...loginAdmin.METADATA,
            path: loginAdmin.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace loginAdmin {
  export type Props = {
    /** Admin login credentials */
    body: ITodoListAdmin.ILogin;
  };
  export type Body = ITodoListAdmin.ILogin;
  export type Response = ITodoListAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/admin/login";
  export const random = (): ITodoListAdmin.IAuthorized =>
    typia.random<ITodoListAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: loginAdmin.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: loginAdmin.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
