import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITodoListAdmin } from "../../../../structures/ITodoListAdmin";

/**
 * Refresh administrator tokens.
 *
 * Refresh JWT access and refresh tokens for an authenticated administrator
 * using a valid refresh token. Ensures continuous secure access without
 * requiring re-login. This endpoint requires a valid refresh token in the
 * request and responds with new JWT tokens for continued access to
 * administrative capabilities.
 *
 * @param props.connection
 * @param props.body Admin token refresh request
 * @setHeader token.access Authorization
 *
 * @path /auth/admin/refresh
 * @accessor api.functional.auth.admin.refresh.refreshAdmin
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refreshAdmin(
  connection: IConnection,
  props: refreshAdmin.Props,
): Promise<refreshAdmin.Response> {
  const output: refreshAdmin.Response =
    true === connection.simulate
      ? refreshAdmin.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refreshAdmin.METADATA,
            path: refreshAdmin.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refreshAdmin {
  export type Props = {
    /** Admin token refresh request */
    body: ITodoListAdmin.IRefresh;
  };
  export type Body = ITodoListAdmin.IRefresh;
  export type Response = ITodoListAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/admin/refresh";
  export const random = (): ITodoListAdmin.IAuthorized =>
    typia.random<ITodoListAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refreshAdmin.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refreshAdmin.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
